.TH xcb_query_font 3  today "XCB" "XCB Requests"
.ad l
.SH NAME
xcb_query_font \- query font metrics
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_query_font_cookie_t \fBxcb_query_font\fP(xcb_connection_t\ *\fIconn\fP, xcb_fontable_t\ \fIfont\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_query_font_reply_t {
    uint8_t        \fIresponse_type\fP;
    uint8_t        \fIpad0\fP;
    uint16_t       \fIsequence\fP;
    uint32_t       \fIlength\fP;
    xcb_charinfo_t \fImin_bounds\fP;
    uint8_t        \fIpad1\fP[4];
    xcb_charinfo_t \fImax_bounds\fP;
    uint8_t        \fIpad2\fP[4];
    uint16_t       \fImin_char_or_byte2\fP;
    uint16_t       \fImax_char_or_byte2\fP;
    uint16_t       \fIdefault_char\fP;
    uint16_t       \fIproperties_len\fP;
    uint8_t        \fIdraw_direction\fP;
    uint8_t        \fImin_byte1\fP;
    uint8_t        \fImax_byte1\fP;
    uint8_t        \fIall_chars_exist\fP;
    int16_t        \fIfont_ascent\fP;
    int16_t        \fIfont_descent\fP;
    uint32_t       \fIchar_infos_len\fP;
} \fBxcb_query_font_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_query_font_reply_t *\fBxcb_query_font_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_query_font_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.SS Reply accessors
.HP
xcb_fontprop_t *\fBxcb_query_font_properties\fP(const xcb_query_font_request_t *\fIreply\fP);
.HP
int \fBxcb_query_font_properties_length\fP(const xcb_query_font_reply_t *\fIreply\fP);
.HP
xcb_fontprop_iterator_t \fBxcb_query_font_properties_iterator\fP(const xcb_query_font_reply_t *\fIreply\fP);
.HP
xcb_charinfo_t *\fBxcb_query_font_char_infos\fP(const xcb_query_font_request_t *\fIreply\fP);
.HP
int \fBxcb_query_font_char_infos_length\fP(const xcb_query_font_reply_t *\fIreply\fP);
.HP
xcb_charinfo_iterator_t \fBxcb_query_font_char_infos_iterator\fP(const xcb_query_font_reply_t *\fIreply\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIfont\fP 1i
The fontable (Font or Graphics Context) to query.
.SH DESCRIPTION
Queries information associated with the font.
.SH RETURN VALUE
TODO: not yet generated
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO

.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
